version: "3.9"

volumes:
  chat1_backend_public:
    external: true
    name: chat1_backend_public
  chat1_backend_private:
    external: true
    name: chat1_backend_private

networks:
  network_public:
    external: true
    name: network_public

services:

  ticketz_backend:
    image: ghcr.io/ticketz-oss/ticketz-backend:latest
    volumes:
      - chat1_backend_public:/usr/src/app/public
      - chat1_backend_private:/usr/src/app/private
    environment:
      - FRONTEND_HOST=app.domain.com
      - BACKEND_PATH=/backend
      - EMAIL_ADDRESS=admin@example.com
      - TZ=America/Recife
      - BACKEND_URL=https://app.domain.com/backend
      - FRONTEND_URL=https://app.domain.com
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=ticketz
      - DB_PASS=dbpassword
      - REDIS_URI=redis://redis:6379/
      - REDIS_OPT_LIMITER_MAX=1
      - REDIS_OPT_LIMITER_DURATION=3000
      - USER_LIMIT=10000
      - CONNECTIONS_LIMIT=100000
      - CLOSED_SEND_BY_ME=true
      - VERIFY_TOKEN=ticketz
    networks:
       network_public:
         aliases:
          - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    

  ticketz_frontend:
    image: ghcr.io/ticketz-oss/ticketz-frontend:latest
    volumes:
      - chat1_backend_public:/var/www/backend-public
    environment:
      - FRONTEND_HOST=app.domain.com
      - BACKEND_PATH=/backend
      - BACKEND_HOST=app.domain.com
      - BACKEND_PROTOCOL=https
      - BACKEND_PORT=443
      - EMAIL_ADDRESS=admin@example.com
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.ticketz_frontend.rule=Host(`app.domain.com`)
        - traefik.http.routers.ticketz_frontend.entrypoints=websecure
        - traefik.http.routers.ticketz_frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.ticketz_frontend.loadbalancer.server.port=80

  ticketz_watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1800 --cleanup
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
